### PR TITLE
MAINT: Update jupyterbook build infrastructure

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates the build infrastructure to the latest versions.

### CODE REVIEW

**Comment by mmcky** [comment]
@jbrightuniverse ok I think that is all the commits I will need to do. I tested the latest `jupyterbook` first, updated to the new mathjax config and then updated the theme. So the last preview build is what you should take a look at. Thank you.

**Comment by mmcky** [comment]
@AakashGfude I have:

1. upgraded `quantecon-book-theme`
2. checked github actions

the [`_build` folder artifact](https://github.com/QuantEcon/lecture-julia.myst/actions/runs/1781761440) now appears correct but still getting an issue with the download link. 

Can you check the `html` for me

https://61f9eb46e532e3665f445e06--vibrant-allen-f39ec9.netlify.app/getting_started_julia/julia_essentials.html

**Comment by mmcky** [comment]
thanks @AakashGfude for the patch to `quantecon-book-theme==0.3.1`.

The preview is now working correctly for the `ipynb` download link. @jbrightuniverse @jlperla feel free to merge when you're happy after your review and tag a publish.

**Comment by jlperla** [comment]
@mmcky great. It may make sense for you guys should merge it and tell @jbrightuniverse what you want us to doublecheck

**Comment by mmcky** [comment]
Sure. I'll merge this now. @jbrightuniverse once a preview is built on `master` you should be able to take a quick look. If you're happpy (i.e. no changes -- except fixed download link) -- please then trigger a release.

**Pull request merged**
