### PR TITLE
🐛 FIX: changes in source file for pdf build

### PR DESCRIPTION
**Pull request by AakashGfude**

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude the `table of content` and `contents` links don't seem to be clickable on the preview `pdf`

**Comment by AakashGfude** [comment]
> @AakashGfude the `table of content` and `contents` links don't seem to be clickable on the preview `pdf`

ooh no !! I will rebuild and see, else need to debug.

**Comment by AakashGfude** [comment]
It looks okay when building locally. Wonder what the reason is.

**Comment by AakashGfude** [comment]
The CI is using sphinxv4 to build and is throwing errors because of this issue: https://github.com/QuantEcon/quantecon-book-theme/issues/172 .
Will find a concrete solution for that issue and then merge with updates.

**Comment by mmcky** [comment]
@AakashGfude just checking in on this PR. Is the upstream issue is now resolved.

**Comment by mmcky** [comment]
There is an issue with Jupyter-server that needs investigating but will remove this restriction once that is resolved.

**Comment by mmcky** [comment]
@jlperla this is the latest `pdf` now that this branch is running. 

[quantecon-julia.pdf](https://github.com/QuantEcon/lecture-julia.myst/files/10452972/quantecon-julia.pdf)

@AakashGfude I noticed that the `table of contents` is missing from the pdf. Any ideas?

**Comment by mmcky** [comment]
@AakashGfude I have identified the issue.

When building the Julia lectures if there is generated `math` from code the `ipynb` json blob is

```json
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Our formula is"
     ]
    },
    {
     "data": {
      "text/latex": [
       "$$ \\begin{equation}\n",
       "\\frac{x0}{1 + \\frac{-1 - g}{1 + r}}\n",
       "\\end{equation}\n",
       " $$"
      ],
      "text/plain": [
       "x0 / (1 + (-1 - g) / (1 + r))"
      ]
     },
```

which gets wrapped in tex as

```latex
\begin{sphinxuseclass}{cell_output}
\begin{sphinxVerbatim}[commandchars=\\\{\}]
Our formula is
\end{sphinxVerbatim}
\begin{equation*}
\begin{split} \begin{equation}
\frac{x0}{1 + \frac{-1 - g}{1 + r}}
\end{equation}
 \end{split}
\end{equation*}
\end{sphinxuseclass}\end{sphinxVerbatimOutput}
```

and `xelatex` really does not like nested `equation` environments. 

Is this something we could fix in `sphinx-jupyterbook-latex`?

**Comment by mmcky** [comment]
sphinx / Jupyter-book must be interpreting the `$$` that is found in returned latex objects in `Julia`

**Comment by mmcky** [comment]
This could be fixed using `LaTexify` which:

```
using Latexify
latexify(p0)
```

which returns in the `json` blobs

```json
     "data": {
      "text/latex": [
       "\\begin{equation}\n",
       "\\frac{x0}{1 + \\frac{-1 - g}{1 + r}}\n",
       "\\end{equation}\n"
```

returns LaTeX and no markdown wrappers or delimiters

@jlperla do you know any other settings in `Julia` Symbolics that might turn off the markdown math delimiters?

**Comment by mmcky** [comment]
So the `latexify` will return the equation but it is wrapped in `\begin{equation}` such as:

```
      "text/latex": [
       "\\begin{equation}\n",
       "\\frac{x0}{1 + \\frac{-1 - g}{1 + r}}\n",
       "\\end{equation}\n"
      ],
``` 

so we still get double math environments. Will check latexify docs to see if we can not wrap the equation.

**Comment by mmcky** [comment]
@AakashGfude `simply` in the `python` world returns

```json
...
      "text/latex": [
       "$\\displaystyle \\cos{\\left(x \\right)} + 1$"
      ],
      "text/plain": [
       "cos(x) + 1"
      ]
```

which also includes `$` delimiters so I'm now not sure why we are getting double `equation` environments in the latex writer

**Comment by mmcky** [comment]
@jlperla the [7a9d2c7](https://github.com/QuantEcon/lecture-julia.myst/pull/136/commits/7a9d2c7287b1bf91a8b1a633d7ad24fe1d90dbea) should fix the issue in the short term but it isn't pretty. Let me know what you think?

**Comment by jlperla** [comment]
Looks good to me! Thanks for finding a workaround

**Pull request merged**
