### PR TITLE
commenting out random unit tests, iter 2

### PR DESCRIPTION
**Pull request by Alim-faraji**

### CODE REVIEW

**Comment by mmcky** [comment]
@Alim-faraji if you look at the build logs you will see that `opt_tax_recur` is not executing on this build? Similar Issue?

```
WARNING: Execution Failed: /home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/dynamic_programming_squared/opt_tax_recur.md
```

**Comment by mmcky** [comment]
actually @Alim-faraji looking at the logs 

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
@testset begin
  @test M_time_example.G[sHist_l] ≈ [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  #test M_time_example.Θ[sHist_l] .* sim_seq_l[2] ≈ [1.026385289423105, 0.9945696863679917,
                                                     0.9945696863679917, 0.9945696863679917,
                                                     0.9945696863679917, 0.9945696863679917,
                                                     0.9945696863679917]
  @test M_time_example.G[sHist_h] ≈ [0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1]
  #test sim_seq_l[end] ≈ [1.0361020796451619, 1.111111111111111, 1.052459380877434,
                          1.111111111111111, 1.111111111111111, 1.111111111111111]
end
------------------

syntax: "begin" at In[7]:1 expected "end", got "]"

Stacktrace:
 [1] top-level scope
   @ In[7]:6
 [2] eval
   @ ./boot.jl:360 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
LoadError: syntax: "begin" at In[7]:1 expected "end", got "]"
```

Do we have to comment the additional lines for `julia` to ignore them?

**Comment by mmcky** [comment]
@Alim-faraji this is now building all lectures so I will go ahead and merge.

**Comment by Alim-faraji** [comment]
Thanks @mmcky. I used find and replace function in VSCode, and didn't pay attention to multi line tests.

**Pull request merged**
