### PR TITLE
add Symbolics to Project.toml

### PR DESCRIPTION
**Pull request by jbrightuniverse**

### CODE REVIEW

**Comment by DawievLill** [comment]
@jbrightuniverse Thanks for letting me know. Are the other figures generating properly? I don't have an initial idea as to why this might be the case. I will quickly have to go and run the code again to see if I can replicate the error. When I originally ran this I did get a surface plot.

**Comment by jbrightuniverse** [comment]
Every other graph appears to load fine.

**Comment by DawievLill** [comment]
It seems I might need to make slight change to the Symbolics code as well (which is luckily just a quick fix). I am not sure why the 3d graph is not generating properly. 

@jlperla Could you perhaps take a look at the 3d graph? On my side it is working fine, but the deployment doesn't generate the correct figure.

**Comment by jlperla** [comment]
100% agree on dropping the 3d graphs then.  Not worth the trouble.

**Comment by DawievLill** [comment]
@jlperla and @jbrightuniverse Before I make the changes I just want to check something. James picked up that the scale of the figures are different between the Python and Julia lectures. The reason for this is that the value for `b`, which represents MPC, is at 0.9 in the Python lecture. This was not done on purpose (I think). It is a remnant from a `for loop` from a previous code block in the Python code. However, for our model `b = 2/3`, which was the original MPC in the code. Do we change MPC to 0.9 in this last block so that the figures align across lectures? Or do we keep it at 2/3 and change the Python code. 

This might be super trivial, but I wanted to check with you guys. For now, I am just keeping it at 2/3.

**Comment by jlperla** [comment]
@DawievLill   I trust whatever your judgment is on this!

**Pull request merged**
