### PR TITLE
MAINT: Maintenance and Updates

### PR DESCRIPTION
**Pull request by mmcky**
This does a full maintenance review of the `Julia` lectures. 

Includes #238

### CODE REVIEW

**Comment by mmcky** [comment]
@jlperla not sure why Format Markdown Files isn't quite working. Maybe my merge from main?

**Comment by jlperla** [comment]
@mmcky I think it is fine. Probably the merge. The files should be formatted anyways.

**Comment by mmcky** [comment]
Roger that @jlperla this is ready to be merged. Would you like me to go ahead and then issue another publish?

**Comment by jlperla** [comment]
Yeah let's do it! Merge and push a release, and we can check if the toml move over

**Pull request merged**
