### PR TITLE
ENH: Upgrade to Julia 1.7 

### PR DESCRIPTION
**Pull request by jbrightuniverse**

### CODE REVIEW

**Comment by mmcky** [comment]
I am seeing execution failures in the following letures

- [ ] dynamic_programming_squared/dyn_stack.md
- [ ] dynamic_programming/lqcontrol.md
- [ ] tools_and_techniques/stationary_densities.md
- [ ] tools_and_techniques/finite_markov.md
- [ ] dynamic_programming/jv.md
- [ ] dynamic_programming_squared/lqramsey.md
- [ ] dynamic_programming/mccall_model.md
- [ ] multi_agent_models/arellano.md
- [ ] time_series_models/multiplicative_functionals.md
- [ ] dynamic_programming_squared/amss.md

**Comment by jlperla** [comment]
@jbrightuniverse worth going through them all, but I would bump package versions in the manifest on 1.7.1 with an`] up` first (and mKe sure nothing is holding back key packages like Plots in the dependency tree as usual). 

Julia package updates have been far better recently, but they still have issues.

**Comment by jlperla** [comment]
@mmcky the reason the CI passed despite these issues was #84 ?

**Comment by mmcky** [comment]
@jlperla that's correct -- There is no `error` on warning set so the CI doesn't fail. However the first task for building notebooks will execute them -- in this case it is the `sphinx-tojupyter` build of the download notebooks.

**Comment by mmcky** [comment]
I could merge the `-W` update into this branch if that would help. Then we merge `julia==1.7` without warnings as a milestone.

**Comment by jlperla** [comment]
Totally up to you guys, I will stay out of it!

**Comment by mmcky** [comment]
@jbrightuniverse I have enabled error on warnings so that it is more obvious when things need to be fixed. I think it would be great if we can resolve ALL warnings as that is the baseline we need for high quality publishing builds. I'll help out once you're able to fix the execution issues on the `julia` side

**Comment by jbrightuniverse** [comment]
Should have named the most recent commit, but I resolved the `Random` issues that appeared to cause the majority of the failing tests (at least, they resolved on my end). There was one instance in `dyn_stack.md` where `@test round(vt_leader[1] + vt_follower[1] - 2*vt_MPE[1], digits = 4) == -3.9708` failed because the number changed to `-3.9707`; I'm not entirely sure why that happened.

**Comment by mmcky** [comment]
@jbrightuniverse I have removed `-W` for now so that it won't error on warnings and will work on that issue in #84

**Pull request merged**
