### PR TITLE
Remove gr(fmt=:png)

### PR DESCRIPTION
**Pull request by jbrightuniverse**

### CODE REVIEW

**Comment by jbrightuniverse** [comment]
@jlperla I double checked the files to make sure I hadn't missed anything and it turns out that there is one and only one file where the line was actually `gr(fmt = :png, size = (900, 500))` which extended the width of some of the plots. Not having this makes the plots less wide, which for all but one of them is okay. The problem is one of the plots now has labels that overlap with each other. Perhaps one fix could be to go and specify size in all instances of `plot()` on this file to maintain parity.

**Comment by jlperla** [comment]
Thanks @jbrightuniverse 

The `fmt=:png` should only be passed in as a keyword arg to the particular `plot` call now when required. We shouldn't ever call `gr(...`, right?

If so, then I just pass in the arg to change the dimension on that one figure, and the default should work for the others?

**Comment by jbrightuniverse** [comment]
`gr()` can be avoided entirely now since yes we can declare a specific size on a plot by plot basis (e.g. just the one plot).
(We can apply it to other ones if the plot points on them seem too close together; they're definitely readable, but I think this might've been one of the reasons for specifying size in the first place).

**Comment by jbrightuniverse** [comment]
https://6145895c5f8f92ec4992aa62--vibrant-allen-f39ec9.netlify.app/tools_and_techniques/lln_clt.html#lln is the current version

https://julia.quantecon.org/tools_and_techniques/lln_clt.html is the original version

@jlperla the first few plots in the new version do have a few overlapping dots (but they are just dots) and I'm not sure if its necessary to go in and widen them (it wouldn't take any effort to do so, however).

**Comment by jlperla** [comment]
@jbrightuniverse I trust your judgment on this. Merge things when you are happy with them, and don't worry about things being a little imperfect one of the lectures. If the sizes are inconsistent, then that is fine if the figures are themselves visible and correct.

**Pull request merged**
