### PR TITLE
remove Dierckx

### PR DESCRIPTION
**Pull request by jbrightuniverse**

### CODE REVIEW

**Comment by jbrightuniverse** [comment]
@jlperla so far I've left the `LinInterp` stuff alone because that's a `QuantEcon.jl` function, not a `Dierckx` one (and will need extra speedtesting).

Also, what is the reference to `general_packages.md` that I'm supposed to change? I can't seem to find it.

Additionally, I was not yet able to implement the function wrapper because apparently a cell after the first plotting cell relies on variables from that one, so I would need to go and hunt for any other such dependencies in order to get those additional cells to continue working.

**Comment by jlperla** [comment]
Oh, we want to get rid of that and use the interpolations one, or maybe the data interpolations one just for consistency. But I want to avoid all use of that interpolator. No need to do a speed to test for this one.

**Comment by jlperla** [comment]
No need to do the function wrapper. The whole code would need to be optimized, so it isn't worth these smaller things

**Comment by jlperla** [comment]
Finally, don't worry about the references to the general_packages either. I can do that later

**Comment by jbrightuniverse** [comment]
When switching `LinInterp` to `LinearInterpolation` from `DataInterpolations` (with the appropriate argument reordering), most charts are still ok, but this one which previously was:
image
no longer has straight lines at the end:
image

**Pull request merged**
