### PR TITLE
fixed plot labels

### PR DESCRIPTION
**Pull request by floswald**
Plots.jl wants a row vector for plot labels here.

### CODE REVIEW

**Comment by jlperla** [comment]
Thanks @floswald ! .  @jbrightuniverse   Can you take a look at this?

**Comment by jbrightuniverse** [comment]
@jlperla looks good to me - this was before:
image
and this is after:
image

**Comment by jlperla** [comment]
Looks good, I will merge.

**Comment by jlperla** [comment]
@floswald thanks for the contribution!

**Comment by floswald** [comment]
Thanks for the ace material!

**Pull request merged**
